# Generated by Django 2.0.2 on 2018-02-12 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id_affiliation', models.AutoField(primary_key=True, serialize=False)),
                ('affiliation', models.CharField(max_length=100)),
                ('grid', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id_author', models.AutoField(primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('current_affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ntgBackend.Affiliation')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorAlias',
            fields=[
                ('id_authoralias', models.AutoField(primary_key=True, serialize=False)),
                ('alias', models.CharField(max_length=30)),
                ('id_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ntgBackend.Author')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorScore',
            fields=[
                ('id_authorscore', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('publication_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('id_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ntgBackend.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id_keyword', models.AutoField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword_Publication',
            fields=[
                ('id_keyword_publication', models.AutoField(primary_key=True, serialize=False)),
                ('id_keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ntgBackend.Keyword')),
            ],
        ),
        migrations.CreateModel(
            name='KeywordAlias',
            fields=[
                ('id_keywordalias', models.AutoField(primary_key=True, serialize=False)),
                ('alias', models.CharField(max_length=50)),
                ('id_keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ntgBackend.Keyword')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id_publication', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('abstract', models.TextField()),
                ('publication_date', models.DateField()),
                ('pmcid', models.CharField(blank=True, max_length=30, null=True)),
                ('pmid', models.CharField(blank=True, max_length=30, null=True)),
                ('doi', models.CharField(blank=True, max_length=30, null=True)),
                ('other_id', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=50, null=True)),
                ('citations', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publication_Author',
            fields=[
                ('id_publication_author', models.AutoField(primary_key=True, serialize=False)),
                ('id_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ntgBackend.Author')),
                ('id_publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ntgBackend.Publication')),
            ],
        ),
        migrations.CreateModel(
            name='Publication_Author_Affiliation',
            fields=[
                ('id_publication_author_affiliation', models.AutoField(primary_key=True, serialize=False)),
                ('id_affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ntgBackend.Affiliation')),
                ('id_publication_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ntgBackend.Publication_Author')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id_publisher', models.AutoField(primary_key=True, serialize=False)),
                ('publisher_name', models.CharField(max_length=50)),
                ('issn', models.CharField(max_length=30, null=True)),
                ('publishing_group', models.CharField(max_length=50, null=True)),
                ('publication_year', models.PositiveSmallIntegerField(null=True)),
                ('website', models.URLField(null=True)),
                ('impact_factor', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublisherType',
            fields=[
                ('id_publishertype', models.AutoField(primary_key=True, serialize=False)),
                ('publisher_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='publisher',
            name='id_publishertype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ntgBackend.PublisherType'),
        ),
        migrations.AddField(
            model_name='publication',
            name='id_publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ntgBackend.Publisher'),
        ),
        migrations.AddField(
            model_name='keyword_publication',
            name='id_publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ntgBackend.Publication'),
        ),
        migrations.AlterUniqueTogether(
            name='publication_author_affiliation',
            unique_together={('id_publication_author', 'id_affiliation')},
        ),
        migrations.AlterUniqueTogether(
            name='publication_author',
            unique_together={('id_publication', 'id_author')},
        ),
        migrations.AlterUniqueTogether(
            name='keyword_publication',
            unique_together={('id_publication', 'id_keyword')},
        ),
    ]
