# Generated by Django 2.0.2 on 2018-09-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntgBackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='keywords',
            field=models.ManyToManyField(through='ntgBackend.Keyword_Publication', to='ntgBackend.Keyword'),
        ),
    ]
